apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: mbongeni/payments
          env: 
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID 
              value: olyup
            - name: MONGO_URI
              value: 'mongodb+srv://olyup:Monkeyland2@olyup.m7wfhdp.mongodb.net/payments?retryWrites=true&w=majority'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            
            
            
            
    
--- 

apiVersion: v1 
kind: Service
metadata: 
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000