export const sports = [
  'Soccer',
  'Olympic Weightlifting',
  'Football',
  'Rugby',
  'Ice Hockey',
  'Basketball',
  'Strength Coach',
  'Gymnastics',
  'Powerlifting',
  'Bodybuilding',
  'VolleyBall',
  'Tennis',
  'Table Tennis',
  'Badminton',
  'Lacrosse',
  'Field Hockey',
  'Cricket',
  'Track & Field',
  'Cross Country',
  'Personal Trainer',
  'Golf',
  'Baseball',
  'Swimming',
  'Skiing',
  'Therapist',
  'Wrestling',
  'Taekwondo',
  'Karate',
  'Boxing',
  'Ice Skating',
  'Cycling',
  'Archery',
  'Rock Climbing',
  'Fencing',
  'Judo',
  'Kickboxing',
];
