apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
    name: ingress-service
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
spec: 
    rules:
      - host: olyup.dev
        http:
          paths:
            - path: /api/users/?(.*)
              backend:
                serviceName: auth-srv
                servicePort: 3000
            - path: /api/athletic/?(.*)
              backend:
                serviceName: athletic-srv
                servicePort: 3000
            - path: /api/exercise/?(.*)
              backend:
                serviceName: exercise-srv
                servicePort: 3000
            - path: /?(.*)
              backend:
                serviceName: client-srv
                servicePort: 3000
            
          
         
      
    